/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package gradle_project_start.app

import gradle_project_start.todoapp.ToDoApp

fun main() {
    val todoapp = ToDoApp()
    todoapp.addNewTask(ToDoApp.TaskToDo("do server", false))
    println(todoapp.getActualToDoList()[0]?.name)
}
