/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package gradle_project_start.app

class MessageUtils {
    companion object {
        fun getMessage(): String = "Hello      World!"
    }
}
