/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("gradle_project_start.kotlin-library-conventions")
}

dependencies {
    testImplementation ("org.junit.jupiter:junit-jupiter-api:5.6.0")
    testRuntimeOnly ("org.junit.jupiter:junit-jupiter-engine")
    testImplementation ("io.strikt:strikt-core:0.34.0")
}
