/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("gradle_project_start.kotlin-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":todoapp"))
}

application {
    // Define the main class for the application.
    mainClass.set("gradle_project_start.app.AppKt")
}
